In [11]:
import numpy as np
SCREEN_SIZE = (600, 500)
CELL_SIZE = 2
np.zeros(
            (SCREEN_SIZE[1]//CELL_SIZE, SCREEN_SIZE[0]//CELL_SIZE)).shape

(250, 300)

In [4]:
x=-10
x%=20
x

10

In [7]:
[(10+145*x, 110+145*y) for y in range(4) for x in range(4)]

[(10, 110),
 (155, 110),
 (300, 110),
 (445, 110),
 (10, 255),
 (155, 255),
 (300, 255),
 (445, 255),
 (10, 400),
 (155, 400),
 (300, 400),
 (445, 400),
 (10, 545),
 (155, 545),
 (300, 545),
 (445, 545)]

In [16]:
import numpy as np
for i in np.zeros((4,4)):
    print(i)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [29]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
print(np.rot90(a,-1))
a


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
b=np.array([2,4,2,2])[::-1]
row_updated=[]
row_=np.append(b[b.nonzero()],0)
print(row_)

flag=True

for idx, ele in enumerate(row_[:-1]):
    if ele == row_[idx+1] and flag:
        row_updated.append(2*ele)
        print(row_updated)
        flag=False
    else:
        if flag:
            row_updated.append(ele)
        print(row_updated)
        flag=True

while len(row_updated) < 4:
                row_updated = np.append(row_updated, 0)
print("DOne:", row_updated)

[2 2 4 2 0]
[4]
[4]
[4, 4]
[4, 4, 2]
DOne: [4 4 2 0]


In [81]:
x, y = np.random.choice(
            4, 2, replace=False), np.random.choice(4, 2, replace=True)
x

array([2, 3])

In [97]:
points = [(x, y) for x in range(4) for y in range(4)]
board = np.zeros((4, 4))

# 2つの座標をランダムに選択（重複なし）
selected_points = np.random.choice(len(points), 2, replace=False)
init_loc = [points[i] for i in selected_points]

for loc in init_loc:
    board[loc]=np.random.choice([2,4])

board


array([[2., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
board[1,:]=np.array([1,1,1,1])

In [134]:
board

array([[2., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 4., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
a=8
len(format(8,'b')[1:])

3

In [124]:
points = [(x, y) for x in range(4) for y in range(4)]
occupied_loc=np.argwhere(board.flatten()==0)
new_points=[]
for loc in occupied_loc:
    new_points.append(points[loc[0]])
new_points
np.random.choice(len(new_points), 1, replace=False)

array([2])

In [130]:
a=[]
a is []

False